### ISSUE TITLE
`create-startup.sh` needs to change `tez-site.xml` as well

### ISSUE THREAD

**Issue by karth295** [jasonmar/dataproc-client#5]
By default, `tez-ui.history-url.base` is set to the single node cluster's hostname rather than the cluster hostname. This causes a confusing error: when you click on ApplicationMaster in the YARN UI, it tries to redirect to a hostname that doesn't exist and you see ERR_SOCKS_CONNECTION_FAILED (when using a SOCKS proxy). If you weren't using a SOCKS proxy, I believe you'd see a connection timeout.

**Comment by jasonmar** [comment]
Thanks, this has been added to `config-files` list in latest revision
