### ISSUE TITLE
dataproc-client should *not* start from a single node dataproc cluster

### ISSUE THREAD

**Issue by karth295** [jasonmar/dataproc-client#7]
If you create a single node cluster, shut it down, then start it again, you'll end up starting all the daemons again -- the Dataproc Agent, NameNode, ResourceManager, NodeManager, DataNode, Spark HistoryServer, MR HistoryServer, and App Timeline Server.

1) Since the cluster is pointed at the target cluster, I believe the NM/DN will try to register as worker of the target cluster. Today, Dataproc whitelists nodes that are allowed to join, so the client won't end up being a worker. But we are planning to remove the whitelist as part of a scaling revamp in Q4.
2) I assume you'll end up sending metrics and logs to Stackdriver, as well.

Two better options come to mind:
1) Create a Debian or Ubuntu GCE VM and just install packages from Dataproc's bigtop repo.

2) Boot a GCE VM directly from Dataproc's base image (which has all packages pre installed). This isn't documented behavior, but Dataproc's base images are not configured to start the daemons by default. Instead, they only start daemons when created through the Dataproc API.

Neither of these are perfect options, because there may be classpath changes that happen when booting a Dataproc cluster. For example, I believe adding the GCS connector to the classpath happens only when booting through the API.

**Comment by jasonmar** [comment]
Thanks for reporting this, the services are now disabled by a `disable-services.sh` added in latest revision
